### ISSUE TITLE
Run on horizontal terminal

### ISSUE THREAD

**Issue by EpsilonKu** [MarcHamamji/runner.nvim#4]
Will be good to have optino run horizontal split (float also).

**Comment by EpsilonKu** [comment]
Ok, I can pr this holidays. Can I pr it?

**Comment by MarcHamamji** [comment]
Yes! Feel free to open a PR.
By the way, I was thinking about refactoring the code so the handlers are stored in tables instead of just functions, but I'll probably work on this during the holidays, too.
But for now you can work on it
Thanks 😊

**Comment by EpsilonKu** [comment]
Sorry for late reply(had unplanned thing on holidays). I guess better to make it on setup. So I will add setup to plugin and make it optional.

**Comment by MarcHamamji** [comment]
Yes, I think using a setup function for this is the best way.
